-- LEGACY MIGRATION — now a no-op.
-- The BSData parser (parse-bsdata.js) now correctly assigns chapter-specific
-- detachments to their owning faction by reading notInstanceOf modifiers
-- from the .cat XML files. This migration previously attempted to do the
-- same thing manually but had incorrect mappings (e.g. Librarius Conclave
-- was incorrectly moved to Dark Angels, partial name matches like 'Lion'
-- failed to match 'Lion's Blade Task Force').
--
-- All UPDATE statements have been removed. The Index cleanup DO block is
-- also removed since the parser no longer creates Index placeholder
-- detachments for chapters that receive routed detachments.
