-- Sync missing enhancements to production
-- Generated by scripts/generate-enhancement-sync.js
--
-- These enhancements exist in the seed file but were missing from production
-- due to BSData parser gaps (now fixed) and detachment ID mismatches
-- (where the seed used different detachment UUIDs than what production has).
--
-- Each insert looks up the detachment_id by (faction_name, detachment_name)
-- at runtime, so it works regardless of which UUID production has stored.

-- Space Marines :: Librarius Conclave (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'e2f962dc-550b-7606-d1c3-1ee7872991a5',
       d.id,
       'Prescience',
       25,
       'Adeptus Astartes Psyker model only (excluding Terminator models). Once per turn, when an enemy
unit ends a Normal, Advance or Fall Back move within 9" of the bearer’s unit, the bearer’s unit can
make a Normal move of up to D6", or up to 6" instead if the Divination Discipline is active for your army'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Space Marines' AND d.name = 'Librarius Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '98d1bedb-d472-84cd-2887-d6bded4e1094',
       d.id,
       'Celerity',
       30,
       'Adeptus Astartes Psyker model only. The bearer’s unit is eligible to declare a charge in a turn in which it Advanced, and if the Biomancy Discipline is active for your army, it is eligible to declare a charge in a turn in which it Fell Back.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Space Marines' AND d.name = 'Librarius Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '2e45ae10-f4cf-7cf1-8159-316be5615def',
       d.id,
       'Obfuscation',
       20,
       'Adeptus Astartes Psyker model only. Enemy units cannot use the Fire Overwatch Stratagem to shoot
at the bearer’s unit, and if the Telepathy Discipline is active for your army, the bearer’s unit cannot be
targeted by ranged attacks unless the attacking model is within 18".'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Space Marines' AND d.name = 'Librarius Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'd66bbef5-5895-68ac-4cf7-f07bc3acdeaa',
       d.id,
       'Fusillade',
       35,
       'Adeptus Astartes Psyker model only. Ranged weapons equipped by models in the bearer’s unit have
the [ANTI‑MONSTER 5+] and [ANTI‑VEHICLE 5+] abilities, and:


■ The [SUSTAINED HITS 1] ability if the Pyromancy
Discipline is active for your army.
■ Add 6" to the Range characteristic of those
weapons if the Telekinesis Discipline is active for
your army'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Space Marines' AND d.name = 'Librarius Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Custodes :: Shield Host (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'fa47eae3-7a37-9fa8-5b30-0045cfe51b02',
       d.id,
       'Castellan''s Mark',
       20,
       'After both players have deployed their armies, you can select up to two ADEPTUS CUSTODES units from your army (excluding ANATHEMA PSYKANA units) and redeploy all of those units. When doing so, any of those units can be placed into Strategic Reserves, regardless of how  any units are already in Strategic Reserves.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Shield Host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '5c3a43b9-3a93-4a0b-d2d2-e9a99959f555',
       d.id,
       'Panoptispex',
       5,
       'While the bearer is leading a unit, ranged weapons equipped by models in that unit have the [IGNORES COVER] ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Shield Host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '04243ac9-0ac2-2345-038a-6b0ea92afb54',
       d.id,
       'From the Hall of Armouries',
       25,
       'Add 1 to the Strength and Damage characteristics of the bearer''s melee weapons.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Shield Host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'c24b415d-afc8-46e7-1219-840b9115eb9e',
       d.id,
       'Auric Mantle',
       15,
       '**^^Shield-Captain^^** or **^^Blade Champion^^** model only. Add 2 to the bearer''s Wounds characteristic.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Shield Host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Custodes :: Talons of the Emperor (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '5dfcd1e3-1f58-53fb-be6d-71a1f47b45ba',
       d.id,
       'Radiant Mantle',
       30,
       'Each time an attack targets the bearer''s unit, if the attacking model is within 12", subtract 1 from the Hit roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Talons of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '78ed0720-5169-bc87-c7c8-ff94014c4cb1',
       d.id,
       'Aegis Projector',
       20,
       'Once per turn, the first time a saving throw is failed for the bearer''s unit, change the Damage characteristic of that attack to 0.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Talons of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'd27ffd97-34b1-4203-bd9f-c309f65629d5',
       d.id,
       'Gift of Terran Artifice',
       15,
       'Each time the bearer makes a melee attack, add 1 to the Wound roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Talons of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '104ea048-2e0b-fc67-f1eb-c5e8d5788b3e',
       d.id,
       'Champion of the Imperium',
       25,
       'The range of the bearer’s Null Aegis or Deadly Unity ability (see left) is increased to 9".'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Talons of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Custodes :: Null Maiden Vigil (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '41dce3a8-b464-5283-8e37-50aa2eb61567',
       d.id,
       'Raptor Blade',
       5,
       'Add 1 to the Attacks, Strength and Damage characteristics of the bearer''s melee weapons. While the bearer is within Engagement Range of one or more enemy **^^Psyker^^** units that are Battle-shocked, add 2 to the Attacks, Strength and Damage characteristics of the bearer''s melee weapons instead.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Null Maiden Vigil'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'd09d9401-0c1a-4c19-3734-40a3274405dd',
       d.id,
       'Enhanced Voidsheen Cloak',
       10,
       'Each time an attack is allocated to the bearer, subtract 1 from the Damage characteristic of that attack. If that attack was made by a **^^Psyker^^** or Battle-shocked model, change the Damage characteristic of that attack to 1 instead.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Null Maiden Vigil'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'b0bd1ba1-881b-c2ab-1ea1-88fc13bc9cc3',
       d.id,
       'Huntress'' Eye',
       15,
       'In your Command phase, select one enemy unit within 12" of the bearer. That unit must take a Battle-shock test.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Null Maiden Vigil'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '1e3557ab-7d57-4162-a77b-d17c6924ed42',
       d.id,
       'Oblivion Knight',
       25,
       'While the bearer is leading a unit, each time a model in that unit makes an attack, add 1 to the Hit roll. If that attack targeted an enemy **^^Psyker^^** unit, add 1 to the Wound roll as well.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Null Maiden Vigil'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Custodes :: Auric Champions (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '6eb3431a-ee45-2ecb-627d-8c309c40e9c9',
       d.id,
       'Blade Imperator',
       25,
       'Each time the bearer''s unit ends a Charge move, select one enemy unit within Engagement Range of the bearer and roll one D6: on a 4+, that enemy unit suffers D3 mortal wounds. Once per battle, when the bearer''s unit ends a Charge move, all enemy units within 6" of the bearer must take a Battle-shock test.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Auric Champions'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'ea733c33-58c1-07cf-f49d-ddddcdcf1893',
       d.id,
       'Inspirational Exemplar',
       10,
       'The bearer has a Leadership characteristic of 5+. Once per battle, at the start of any phase, you can select one friendly **^^Adeptus Custodes^^** unit that is Battle-shocked and within 12" of the bearer: that unit is no longer Battle-shocked.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Auric Champions'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '61ceb12b-b6fc-1bed-3e23-6e360f8b90b2',
       d.id,
       'Veiled Blade',
       25,
       'Add 2 to the Attacks characteristic of the bearer''s melee weapons. Once per battle, at the start of any Command phase, triple the bearer''s Objective Control characteristic until the end of the turn.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Auric Champions'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'fb59fbfa-fbd5-7caa-9d3e-d50d0bef268e',
       d.id,
       'Martial Philosopher',
       30,
       'The bearer''s unit is eligible to shoot and/or declare a charge in a turn in which it Fell Back. Once per battle, when an enemy unit ends a Normal, Advance or Fall Back move within 9" of the bearer, if the bearer''s unit is not within Engagement Range of one or more enemy units, it can make a Normal move of up to 6".'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Auric Champions'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Custodes :: Solar Spearhead (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '6f28b1b6-1cdf-79c4-8a4c-8889278e4f78',
       d.id,
       'Honoured Fallen (Aura)',
       15,
       'ADEPTUS CUSTODES VEHICLE model only. While a friendly ADEPTUS CUSTODES INFANTRY or ADEPTUS CUSTODES MOUNTED unit is within 6" of the bearer, each time a model in that unit makes  an attack, re‑roll a Hit roll of 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Solar Spearhead'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '077b20d5-6df5-888a-2519-b672c853a700',
       d.id,
       'Augury Uplink',
       35,
       'ADEPTUS CUSTODES model only. The bearer has the Feel No Pain 5+ ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Solar Spearhead'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '65cd7631-4ef2-8b83-33bd-3d735c4b5669',
       d.id,
       'Adamantine Talisman',
       25,
       '**^^Adeptus Custodes^^** model only. Improve the Attacks, Strength and Damage characteristics of melee weapons equipped by the bearer by 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Solar Spearhead'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '280d7372-fa1e-a7ab-6dc2-5f48b7a1ed8d',
       d.id,
       'Veteran of the Kataphraktoi',
       10,
       'ADEPTUS CUSTODES INFANTRY or ADEPTUS CUSTODES MOUNTED model only. In your Command phase, select one ADEPTUS CUSTODES VEHICLE or ADEPTUS CUSTODES MOUNTED unit within 6" of the bearer. Until the start of your next Command phase, that unit is eligible to shoot in a turn in which it Fell Back.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Solar Spearhead'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Custodes :: Lions of the Emperor (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '5622b4a3-c882-02d2-fb03-f7a74680c577',
       d.id,
       'Superior Creation',
       25,
       '**^^Adeptus Custodes Infantry^^** model only. The first time the bearer is destroyed, roll one D6 at the end of the phase. On a 2+, set the bearer back up on the battlefield, as close as possible to where it was destroyed and not within Engagement Range of one or more enemy units, with its full wounds remaining.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Lions of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '0290de70-e8f7-5154-0a6b-d22c58efacaf',
       d.id,
       'Praesidius',
       25,
       'The bearer has the Lone Operative and Stealth abilities.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Lions of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'ca45b778-fef0-e79b-be48-cef5766cd22f',
       d.id,
       'Fierce Conqueror',
       15,
       'At the start of the Fight phase, until the end of the phase, add 2 to the Attacks characteristic of melee weapons equipped by the bearer for every 5 enemy models within 6" of the bearer (rounding  down).'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Lions of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '1401730b-a275-6aed-11fe-9c0a473685e8',
       d.id,
       'Admonimortis',
       10,
       '**^^Shield‑Captain^^** model only. Improve the Strength characteristic of melee weapons equipped by the bearer by 3, and improve the Armour Penetration and Damage characteristics of those weapons by  1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Custodes' AND d.name = 'Lions of the Emperor'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Mechanicus :: Rad-zone Corps (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'd79c0c44-4fee-f367-41f3-23464fad29f6',
       d.id,
       'Radial Suffusion',
       25,
       'From the second battle round onwards, when resolving the Fallout effect of the Rad-bombardment Detachment rule, if the bearer is on the battlefield, roll one D6 for each enemy unit within 6" of your opponent’s deployment zone, in addition to those that are within your opponent’s deployment zone.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Rad-zone Corps'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'fba893bc-85df-4efe-ce0d-7de872934876',
       d.id,
       'Malphonic Susurrus',
       20,
       'While the bearer is leading a unit, models in that unit have the Stealth ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Rad-zone Corps'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'cc2ecc0a-5b40-5dac-23fe-272f3c7c7463',
       d.id,
       'Peerless Eradicator',
       20,
       'While the bearer is leading a unit, ranged weapons equipped by models in that unit have the [SUSTAINED HITS 1] ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Rad-zone Corps'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'c3e67b0a-0403-4d4c-0985-f0a2f875e969',
       d.id,
       'Autoclavic Denounciation',
       15,
       'Ranged weapons equipped by the bearer have the [ANTI-INFANTRY 2+] and [ANTI-MONSTER 4+] abilities.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Rad-zone Corps'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Mechanicus :: Skitarii Hunter Cohort (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'bd587a92-1d94-2d22-4125-88b2b2a39ce2',
       d.id,
       'Cantic Thrallnet',
       25,
       'At the start of the battle round, you can select one friendly SKITARII unit within 12" of the bearer. Until the start of the next battle round, the Protector Imperative and the Conqueror Imperative are both active for that unit.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Skitarii Hunter Cohort'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '48822bdd-a88d-054f-b13d-de5fe629ddc5',
       d.id,
       'Clandestine Infiltrator',
       20,
       'The bearer, and models in any unit they are leading, have the Infiltrators and Scouts 6" abilities.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Skitarii Hunter Cohort'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '7e0b0e97-5fe0-f3e3-40e7-56a9046c8d53',
       d.id,
       'Veiled Hunter',
       10,
       'After both players have deployed their armies, you can select up to three SKITARII INFANTRY units from your army and redeploy all of those units. When doing so, any of those units can be placed into Strategic Reserves, regardless of how many units are already in Strategic Reserves.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Skitarii Hunter Cohort'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '1e5a12d3-d81e-2548-461f-d1fc8e501a3a',
       d.id,
       'Battle-Sphere Uplink',
       30,
       'In your Shooting phase, after the bearer’s unit has shot, if it is not within Engagement Range of one or more enemy units, that unit can make a Normal move of up to 6". If it does, until the end of the turn, that unit is not eligible to declare a charge.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Skitarii Hunter Cohort'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Mechanicus :: Explorator Maniple (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '7eae80c1-62c1-4992-d828-9143a76edfd2',
       d.id,
       'Magos',
       15,
       'At the end of your Command phase, if the bearer is within range of your Acquisition objective marker, roll one D6: on a 4+, you gain 1CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Explorator Maniple'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'f54c3872-698d-0738-c4cc-a380913cb49c',
       d.id,
       'Genetor',
       25,
       'While the bearer is leading a unit that is within range of your Acquisition objective marker, models in that unit have a 4+ invulnerable save.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Explorator Maniple'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '6ab6d42a-2711-b9fb-9bce-4f222e5c6c6c',
       d.id,
       'Logis',
       20,
       'While the bearer is leading a unit, each time a model in that unit makes an attack that targets a unit within range of your Acquisition objective marker, add 1 to the Hit roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Explorator Maniple'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '1b93b0a5-2e4d-d2ca-3b23-57f87ac9db98',
       d.id,
       'Artisan',
       15,
       'While the bearer is leading a unit that is within range of your Acquisition objective marker, once per phase, you can change the result of one Hit roll, one Wound roll or one saving throw made for that unit to an unmodified 6.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Explorator Maniple'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Mechanicus :: Data-psalm Conclave (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '3430e591-ddca-7192-ff2b-6212b19863a4',
       d.id,
       'Mechanicus Locum',
       10,
       'The bearer has a Leadership characteristic of 6+ and, once per battle, at the start of any phase, you can select one friendly CULT MECHANICUS unit that is Battle-shocked and within 12" of the bearer. That unit is no longer Battle-shocked.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Data-psalm Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '17cd15c5-e09c-068a-5d68-b53ff5fddf9d',
       d.id,
       'Mantle of the Gnosticarch',
       15,
       'Each time an attack is allocated to the bearer, change the Damage characteristic of that attack to 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Data-psalm Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'bbf7a17a-8d9c-e7fd-4a52-5fc004f9a447',
       d.id,
       'Data-blessed Autosermon',
       20,
       'Once per battle, at the start of your Command phase, you can select the Benediction of the Omnissiah you did not select at the start of the first battle round. Until the start of your next Command phase, that Benediction of the Omnissiah is active for the bearer’s unit in addition to the one that is currently active for your army.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Data-psalm Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'c4c327a9-ce8a-b001-0af2-fd80ffe5fb69',
       d.id,
       'Temporcopia',
       25,
       'The bearer’s unit has the Fights First ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Data-psalm Conclave'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Mechanicus :: Cohort Cybernetica (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'f5fc8b0f-ec8d-18b9-eb93-94d1d3ccd903',
       d.id,
       'Necromechanic',
       25,
       'Once per battle round, when a saving throw made for a friendly **^^Legio Cybernetica^^** or **^^Adeptus Mechanicus Vehicle^^** model within 12" of the bearer is failed, the bearer can use this Enhancement. If they do, change the Damage characteristic of that attack to 0.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Cohort Cybernetica'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '6f8030c6-1ea9-a7c3-50c5-d195ed1627fa',
       d.id,
       'Lord of Machines',
       20,
       'Once per turn, at the start of your opponent’s Shooting phase, select one enemy Vehicle unit within 12" of and visible to the bearer. That unit must take a Leadership test: if that test is passed, until the end of the phase, each time a model in that unit makes an attack, subtract 1 from the Hit roll; if that test is failed, that unit is not eligible to shoot this phase.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Cohort Cybernetica'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4412372f-9ef8-92d2-a3f1-a0a88ce7cb4e',
       d.id,
       'Emotionless Clarity',
       15,
       'Once per turn, when a friendly LEGIO CYBERNETICA or ADEPTUS MECHANICUS VEHICLE model with the Deadly Demise ability that is within 12" of the bearer is destroyed, the bearer can use this Enhancement. If it does, do not roll to determine whether any mortal wounds are inflicted as a result of that model’s Deadly Demise ability. Instead, mortal wounds are automatically inflicted.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Cohort Cybernetica'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'fc6d867c-2904-9eca-55d5-c3fcdd963a2d',
       d.id,
       'Arch Negator',
       10,
       'Ranged weapons equipped by the bearer have the [ANTI-VEHICLE 4+] ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Cohort Cybernetica'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Adeptus Mechanicus :: Haloscreed Battleclade (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'efffe965-5f3b-d28a-988a-174a98db6c40',
       d.id,
       'Transoracular Dyad Wafers',
       15,
       'CYBERNETICA DATASMITH model only. When the bearer is attached to a Kastelan Robots unit, until the end of the battle, models in that unit gain the Halo Override keyword. That unit cannot be selected when selecting units as part of the Noospheric Transference Detachment rule.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Haloscreed Battleclade'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '35cca14f-5a1c-cd49-c81e-cbf3bef545bb',
       d.id,
       'Cognitive Reinforcement',
       35,
       'ADEPTUS MECHANICUS model only (excluding CYBERNETICA DATASMITH models). The Conqueror Imperative and Protector Imperative are both active for the bearer’s unit.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Haloscreed Battleclade'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '6bc69939-660b-62c0-1cdc-a3afd5e11585',
       d.id,
       'Sanctified Ordnance',
       10,
       'ADEPTUS MECHANICUS model only. Add 6" to the range characteristic of ranged weapons equipped by models in the bearer’s unit and, each time a Hazardous test is taken for that unit, you can re‑roll the result.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Haloscreed Battleclade'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '7b183b34-a88a-385c-d18f-3f22d878d294',
       d.id,
       'Inloaded Lethality',
       15,
       '**^^Tech-Priest Dominus^^** or **^^Tech-Priest Manipulus^^** model only. Add 3 to the Attacks characteristic of the bearer’s melee weapons and add 1 to the Damage characteristic of the bearer’s melee weapons.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Adeptus Mechanicus' AND d.name = 'Haloscreed Battleclade'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Ultramarines :: Reclamation Force (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4f654f57-9348-41de-5483-1dd69e458fb9',
       d.id,
       'Seals of Reconquest',
       20,
       'Adeptus Astartes model only. Models in the bearer’s unit have a 5+ invulnerable save.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Ultramarines' AND d.name = 'Reclamation Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4d140fac-80a6-894e-b147-c6417936e282',
       d.id,
       'Avenging Avatar (Aura)',
       10,
       'Adeptus Astartes model only. In the Battle‑shock step of your opponent’s Command phase, if an enemy unit that is below its Starting Strength is within 9" of the bearer, that enemy unit must take a Battle‑shock test.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Ultramarines' AND d.name = 'Reclamation Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4430608f-d246-7db6-db77-f54334abb32e',
       d.id,
       'Scroll of Proclamation',
       15,
       'Adeptus Astartes model only. Each time the bearer’s unit declares a charge, if one or more targets of that charge are within range of an objective marker, you can re‑roll the Charge roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Ultramarines' AND d.name = 'Reclamation Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '0bea8aae-a32c-0ae6-8cce-817c41066cc2',
       d.id,
       'Liberatum',
       25,
       'Adeptus Astartes model only. Each time the bearer makes an attack that targets an enemy unit, if the
target is within range of an objective marker, you can re‑roll the Hit roll and you can re‑roll the Wound roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Ultramarines' AND d.name = 'Reclamation Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Agents of the Imperium :: Alien Hunters (Ordo Xenos) (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4c0144b8-0587-1491-c347-a4e7ced50728',
       d.id,
       'Universal Anathema',
       10,
       'Melee weapons equipped by the bearer have the [ANTI-INFANTRY 2+] and [ANTI-MONSTER 4+] abilities'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Alien Hunters (Ordo Xenos)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'c4034eb0-9031-8afd-3458-1953d5d8df51',
       d.id,
       'Blackweave Shroud',
       15,
       'The bearer has the Feel No Pain 4+ ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Alien Hunters (Ordo Xenos)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '331cfc1f-59cb-ba1c-78f4-d51042397f6e',
       d.id,
       'Beacon Angelis',
       30,
       'Models in the bearer''s unit have the Deep Strike ability. In addition, you can target the bearer''s unit with the Rapid Ingress Stratagem for 0CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Alien Hunters (Ordo Xenos)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '19454a5b-6a9b-e052-2b5b-e53de26d8dbe',
       d.id,
       'Amulet of Auto-chastisement',
       25,
       'At the start of your opponent''s Shooting phase, select one enemy VEHICLE unit (excluding TITANIC units) within 12" of and visible to the bearer. That unit must take a Leadership test. If that test is passed, until the end of the phase, each time a model in that unit makes an attack, subtract 1 from the Hit roll. If that test is failed, that unit is not eligible to shoot this phase.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Alien Hunters (Ordo Xenos)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Agents of the Imperium :: Purgation Force (Ordo Hereticus) (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '8e358663-13a4-abda-851d-c77647a8bdcc',
       d.id,
       'Liber Heresius',
       10,
       'After both players have deployed their armies, select up to 3 AGENTS OF THE IMPERIUM units from your army and redeploy them. When doing so, you can set those units up in Strategic Reserves if you wish, regardless of how many units are already in Strategic Reserves.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Purgation Force (Ordo Hereticus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'ab2c95d9-ebe0-21b3-4e44-f38f38df4a25',
       d.id,
       'No Escape',
       25,
       'While an enemy unit is within 6" of the bearer, each time it is selected to Fall Back it must first take a Leadership test. If that test is failed, that unit must Remain Stationary this phase instead.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Purgation Force (Ordo Hereticus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '29d85674-a704-0d46-05de-1203ce052517',
       d.id,
       'Witch Hunter',
       15,
       'While the bearer is leading a unit, each time a model in that unit makes an attack that targets a PSYKER unit, you can re-roll the Hit roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Purgation Force (Ordo Hereticus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'd124b2eb-0e24-98fb-f0c5-9982b1a4b149',
       d.id,
       'Ignis Judicium',
       10,
       'The bearer''s ranged weapons have the [DEVASTATING WOUNDS], [MELTA 1] and [PRECISION] abilities.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Purgation Force (Ordo Hereticus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Agents of the Imperium :: Daemon Hunters (Ordo Malleus) (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '7c7aa267-e7c0-1567-cb59-4ccab13dd31c',
       d.id,
       'Formidable Resolve',
       5,
       'Improve the bearer''s Leadership and Wounds characteristics by 1. Once per battle, at the start of any phase, you can select one friendly Battle-shocked unit within 12" of the bearer. That unit is no longer Battle-shocked.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Daemon Hunters (Ordo Malleus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '972b852b-faa5-d5f6-fc4b-f83d3196f721',
       d.id,
       'Daemon Slayer',
       10,
       'Add 1 to the Attacks characteristic of the bearer''s melee weapons, and those weapons have the **[ANTI-DAEMON 3+]** ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Daemon Hunters (Ordo Malleus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '99aea6e9-7a58-de69-7249-130769516fd8',
       d.id,
       'Grimoire of True Names',
       10,
       'While an enemy unit is within 9" of the bearer, worsen the Leadership characteristic of models in that unit by 1. In addition, while an enemy DAEMON unit is within 9" of the bearer, each time a model in that DAEMON unit makes an attack, subtract 1 from the Hit roll and subtract 1 from the Wound roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Daemon Hunters (Ordo Malleus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'b3ed2aba-3676-4518-24bd-782e43bf353f',
       d.id,
       'Gift of the Prescient',
       20,
       'Once per battle, if the bearer is on the battlefield, you can use the Rapid Ingress Stratagem for 0CP. When doing so, you must target a GREY KNIGHTS TERMINATOR SQUAD unit from your army, and when using the Stratagem, that unit can be set up on the battlefield anywhere that is more than 3" from all enemy units.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Daemon Hunters (Ordo Malleus)'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Agents of the Imperium :: Imperialis Fleet (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'f4585348-06ca-5bff-1744-705d1c50b647',
       d.id,
       'Digital Weapons',
       10,
       'Each time the bearer is selected to fight, roll three D6; for each 4+, one enemy unit within Engagement Range of the bearer suffers 1 mortal wound. Mortal wounds inflicted by this Enhancement are allocated as if they have the [PRECISION] ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Imperialis Fleet'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'b36e3e3b-c887-5b05-3a6d-2288c9b758b0',
       d.id,
       'Clandestine Operation',
       15,
       'At the start of the Declare Battle Formations step, you can select up to three AGENTS OF THE IMPERIUM INFANTRY units from your army (excluding GREY KNIGHTS TERMINATOR SQUAD units) - those units gain the Infiltrators ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Imperialis Fleet'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '463c5cb6-6d9d-624c-8a15-d6620269f313',
       d.id,
       'Fleetmaster',
       20,
       'Once per battle round, you can target the bearer''s unit with the Violent Acquisition, Masters of the Void or Close-quarters Barrage Stratagems for 0CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Imperialis Fleet'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4c2c6cea-173d-f541-cd6e-ce8b51283b7b',
       d.id,
       'Combat Landers',
       10,
       'At the start of the Declare Battle Formations step, you can select up to three VOIDFARERS units from your army - those units gain the Deep Strike ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Imperialis Fleet'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Chaos Space Marines :: Pactbound Zealots (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '95a27cf1-801d-845a-374f-34f118448ac7',
       d.id,
       'Talisman of Burning Blood',
       15,
       'Add 1 to the Attacks and Strength characteristics of the bearer’s melee weapons. Each time the bearer’s unit makes a Dark Pact and does not fail the resulting Leadership test, roll one D3; until the end of the phase, add the result to the Attacks and Strength characteristics of the bearer’s melee weapons instead.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Pactbound Zealots'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4adf4251-4f56-d79d-d72d-bdac5b247f31',
       d.id,
       'Eye of Tzeentch',
       15,
       'Each time the bearer’s unit makes a Dark Pact and does not fail the resulting Leadership test, if the result of that test was 8 or more, you gain 1CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Pactbound Zealots'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '86003f09-e322-70e9-ae49-e280f0703e84',
       d.id,
       'Orbs of Unlife',
       15,
       'At the end of the Fight phase, roll one D6 for every enemy unit within 3" of the bearer, adding 1 to the result if the bearer’s unit made a Dark Pact that phase and did not fail the resulting Leadership test: on a 4+, that enemy unit suffers D3 mortal wounds.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Pactbound Zealots'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'f468a263-7081-d353-5f71-db009d8322d4',
       d.id,
       'Intoxicating Elixir',
       15,
       'The bearer has the Feel No Pain 5+ ability. Each time the bearer shoots or fights, if the bearer’s unit made a Dark Pact this phase and did not fail the resulting Leadership test, after the bearer has resolved those attacks, select one enemy unit that was hit by one or more of those attacks; that enemy unit must take a Battle-shock test.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Pactbound Zealots'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Chaos Space Marines :: Veterans of the Long War (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'da831d9f-c78e-33aa-3f46-5c49add188e2',
       d.id,
       'Warmaster''s Gift',
       15,
       'Each time the bearer makes an attack that targets your focus of hatred, an unmodified successful wound roll of 5+ scores a Critical Wound.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Veterans of the Long War'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4dfd16b3-b311-a4ee-c772-f60478c5b190',
       d.id,
       'Eager for Vengeance',
       20,
       'The bearer''s unit is eligible to shoot and declare a charge in a turn in which it Fell Back. While doing so, each time a model in that unit makes an attack that targets your focus of hatred, add 1 to the Hit roll and each time you select your focus of hatred as a target of that unit''s charge, add 1 to the Charge roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Veterans of the Long War'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '9d7e5dc4-0e34-bc8b-95fa-6d83d2ed08d8',
       d.id,
       'Eye of Abaddon',
       15,
       'While the bearer is on the battlefield, each time your focus of hatred is destroyed, roll one D6; on a 4+, you gain 1CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Veterans of the Long War'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '5007db37-ef90-c9be-581b-c4503bb8791c',
       d.id,
       'Mark of Legend',
       10,
       'Once per turn, you can re-roll one Hit roll, one Wound roll or one saving throw made for the bearer.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Veterans of the Long War'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Chaos Space Marines :: Renegade Raiders (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '215c6d4b-f55c-90df-bfa5-b874e4b07cc5',
       d.id,
       'Despot''s Claim',
       15,
       'At the start of your Command phase, if the bearer is on the battlefield, roll one D6, adding one to the result if the bearer is wholly within 12" of your opponent''s deployment zone; on a 5+, you gain 1CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Renegade Raiders'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'c26d0d01-4b18-eecf-56b5-499fde0cd2ec',
       d.id,
       'Dread Reaver',
       15,
       'Each time the bearer makes a melee attack, if the bearer is wholly within 12" of your opponent''s deployment zone, you can re-roll the Hit roll and you can re-roll the Wound roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Renegade Raiders'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '050b250f-4b75-4067-f293-6f02f0fb0e4c',
       d.id,
       'Mark of the Hound',
       25,
       'Models in the bearer''s unit have the Scouts 6" ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Renegade Raiders'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'e7b650f5-1c3a-749d-1550-6fe1e4b14411',
       d.id,
       'Tyrant''s Lash',
       20,
       'You can re-roll Advance rolls made for the bearer''s unit, and the bearer''s unit is eligible to shoot in a turn in which it Fell Back.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Renegade Raiders'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Chaos Space Marines :: Fellhammer Siege-host (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '10db55e6-167f-54fd-1b80-1387192b726a',
       d.id,
       'Bastion Plate',
       10,
       'Once per battle round, when a saving throw is failed for the bearer''s unit, you can change the Damage characteristic of that attack to 0.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Fellhammer Siege-host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '17714bc9-38a5-a36e-e7ac-ef0f5afbcff1',
       d.id,
       'Ironbound Enmity',
       15,
       'Each time the bearer makes an attack while within range of an objective marker, add 1 to the Wound roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Fellhammer Siege-host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '2c6ac4fb-fece-7b8f-7ae0-77dfae845a67',
       d.id,
       'Warp Tracer',
       20,
       'In your Shooting phase, after the bearer has shot, select one enemy unit hit by one or more of those attacks. Until the end of the phase, that enemy unit cannot have the Benefit of Cover.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Fellhammer Siege-host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '3f5e464c-9e52-240e-8c6e-677184696418',
       d.id,
       'Iron Artifice',
       10,
       'The bearer''s weapons have the [ANTI-VEHICLE 4+] and [ANTI-FORTIFICATION 4+] abilities.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Fellhammer Siege-host'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Chaos Space Marines :: Soulforged Warpack (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'a0f6c6ef-41ee-3e77-8e91-881de2bcebfb',
       d.id,
       'Forge''s Blessing',
       20,
       'In your Command phase, select one friendly HERETIC ASTARTES VEHICLE unit within 12" of the bearer. Until the start of your next Command phase, that unit has the Feel No Pain 6+ ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Soulforged Warpack'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4438a7ea-006b-0007-9d45-32e91ac01051',
       d.id,
       'Invigorated Mechatendrils',
       15,
       'Add 4" to the bearer''s Move characteristic.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Soulforged Warpack'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4ea84183-4dd8-da2c-89df-bffcbcbc2964',
       d.id,
       'Soul Harvester',
       15,
       'While the bearer is on the battlefield, each time an enemy unit within 12" of the bearer is destroyed, roll one D6; on a 5+, you gain 1CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Soulforged Warpack'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '93dfc0e2-bb6a-5042-4584-adfa5b2aea91',
       d.id,
       'Tempting Addendum',
       25,
       'Each time a HERETIC ASTARTES DAEMON VEHICLE from your army invokes its contract while within 3" of the bearer:
- If it suffers one or more mortal wounds as a result of that Dark Pact, add 1 to the number of mortal wounds it suffers.
- Until the end of the phase, each time a model in that unit makes an attack, you can re-roll the Hit roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Soulforged Warpack'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Chaos Space Marines :: Creations of Bile (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '3f104adb-dcc8-8c51-3bb6-9f084cd93ff1',
       d.id,
       'Surgical Precision',
       10,
       'HERETIC ASTARTES model (excluding DAMNED models) only. The bearer’s melee weapons have the [PRECISION] ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Creations of Bile'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'e5961c01-2921-5880-9863-61b15b13a26c',
       d.id,
       'Living Carapace',
       15,
       'CHAOS LORD model only. Add 1 to the bearer’s Wounds characteristic and the bearer has the Feel No Pain 5+ ability.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Creations of Bile'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'f7bc8de9-abe7-99f5-2bde-7499f93bad3e',
       d.id,
       'Helm of All-Seeing',
       25,
       'HERETIC ASTARTES INFANTRY model (excluding DAMNED models) only. Enemy units that are set up on the battlefield from Reserves cannot be set up within 12" of the bearer.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Creations of Bile'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '0ac3267d-17e0-7af2-d457-690470e0da1b',
       d.id,
       'Prime Test Subject',
       35,
       '**^^Heretic Astartes Infantry^^** model (excluding **^^Damned^^** models) only. Add 1 to the Damage characteristic of melee weapons equipped by the bearer. Each time the bearer makes a melee attack, you can re‑roll the Hit roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Chaos Space Marines' AND d.name = 'Creations of Bile'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Emperor's Children :: Coterie of the Conceited (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '1750933b-096b-ba42-b57b-8474615fdd4b',
       d.id,
       'Pledge of Eternal Servitude',
       25,
       'The first time the bearer is destroyed, take a Leadership test for the bearer at the end of the phase. if that test is passed, set the bearer back up on the battlefield as close as possible to where it was destroyed and not within Engagement Range of any enemy units, with D6 wounds remaining (up to its Wounds characteristic).'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Emperor''s Children' AND d.name = 'Coterie of the Conceited'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'cdb2d7a2-021c-4005-df0a-f0bae5ae86cf',
       d.id,
       'Pledge of Dark Glory',
       25,
       'While the bearer is leading a unit, improve the Leadership and Objective Control characteristics of models in that unit by 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Emperor''s Children' AND d.name = 'Coterie of the Conceited'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '0a9a36a5-09f9-7500-253c-9e92532c4d48',
       d.id,
       'Pledge of Mortal Pain',
       15,
       'At the start of your Shooting phase, select one enemy unit within 12" of and visible to the bearer. That unit must take a Leadership test, subtracting 2 from the result if it is Battle-shocked: if failed, that enemy unit suffers 3 mortal wounds.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Emperor''s Children' AND d.name = 'Coterie of the Conceited'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'bb00c636-4dda-4d79-6407-059ff5d01463',
       d.id,
       'Pledge of Unholy Fortune',
       30,
       'Once per turn, after making a Hit roll, a Wound roll or a saving throw for a model in the bearer''s unit, if the bearer is not Battle-shocked, it can use this Enhancement. If it does, treat the result as an unmodified roll of 6 instead.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Emperor''s Children' AND d.name = 'Coterie of the Conceited'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Thousand Sons :: Hexwarp Thrallband (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '31b61fe4-ee97-1f2f-ce88-ea2c90ccb027',
       d.id,
       'Arcane Might',
       20,
       'Add 1 to the Strength characteristic of Psychic weapons equipped by models in the bearer’s unit. While the bearer’s unit is wholly within your army’s Flow of Magic, add 2 to the Strength characteristic of Psychic weapons equipped by models in that unit instead.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Hexwarp Thrallband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'dbf8ce2a-00be-0a00-29d7-b5f8b515b35d',
       d.id,
       'Empowered Manifestation',
       20,
       'While the bearer’s unit is wholly within your army’s Flow of Magic, you can add 6" to the range of Psychic abilities the bearer has that specify a range (including Rituals) and each time a model in the bearer’s unit takes a Hazardous test for a Psychic weapon, you can re‑roll the result.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Hexwarp Thrallband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '189301c5-a130-a171-f13d-f8456740ecf8',
       d.id,
       'Empyric Onslaught',
       25,
       'While the bearer’s unit is wholly within your army’s Flow of Magic, add 3 to the Attacks characteristic of ranged Psychic weapons equipped by the bearer.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Hexwarp Thrallband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '5cc232e2-a40a-aef9-45d3-8c8b71a26bf0',
       d.id,
       'Noctilith Mantle',
       15,
       'While the bearer’s unit is on the battlefield, it is wholly within your army’s Flow of Magic. Models in that unit cannot be selected to use any Rituals.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Hexwarp Thrallband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Thousand Sons :: Changehost of Deceit (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'f86ff9b4-4367-a563-f9da-f437a3d8454c',
       d.id,
       'Nethershriek Mind-eater',
       10,
       'At the start of your Shooting phase, select one enemy unit within 12" of and visible to the bearer. That unit must take a Battle-shock test; if that test is failed, that unit suffers 3 mortal wounds.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Changehost of Deceit'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '52257973-d92a-1c23-183a-3ecd8ed3aa09',
       d.id,
       'Diabolic Servant',
       20,
       'While the bearer is within 6" of one or more friendly ^^**Scintillating Legion^^** units, each time the bearer Channels the Warp, add 1 to the Psychic test result.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Changehost of Deceit'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '1e604581-1467-d8f0-4061-90c6586428d3',
       d.id,
       'Duplicitous Malediction',
       15,
       'After both players have deployed their armies, select up to three ^^**Thousand Sons^^** units from your army and redeploy them. When doing so, you can set those units up in Strategic Reserve if you wish, regardless of how many units are already in Strategic Reserves.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Changehost of Deceit'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'e7fcfb68-e582-cbdc-ef16-b84bc66b55d2',
       d.id,
       'Tome of True Names',
       20,
       'Once per battle, at the start of any phase, the bearer can use this Enhancement. If it does, until the end of the phase, the bearer has a 2+ invulnerable save.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Thousand Sons' AND d.name = 'Changehost of Deceit'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Leagues of Votann :: Needgaârd Oathband (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'f6533196-ebac-18b2-5297-14a7955f3acf',
       d.id,
       'Oathbound Speculator',
       30,
       'Each time a model in the bearer''s unit makes an attack, re-roll a Wound roll of 1. Each time the bearer''s unit is selected to shoot or fight, you can spend 3YP. If you do, until the end of the phase, each time a model in the bearer''s unit makes an attack, add 1 to the Wound roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Leagues of Votann' AND d.name = 'Needgaârd Oathband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '41f9ecd5-5649-6e2f-e70e-11f46aa2aa8f',
       d.id,
       'Dead Reckoning',
       10,
       '**^^Leagues of Votann^^** model only. At the end of the turn, if the bearer is on the battlefield and you spent no YP in that turn, you gain 1YP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Leagues of Votann' AND d.name = 'Needgaârd Oathband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'bc8aea16-ae37-a740-bce5-31332d01f9ab',
       d.id,
       'Iron Ambassador',
       5,
       '**^^Leagues of Votann^^** model equipped with an Autoch-pattern combi-bolter only. Once per battle, when the bearer''s unit is selected to shoot, the bearer can use this Enhancement. If it does, spend up to 3YP, and, until the end of the phase, add the number of YP you just spent to the Damage characteristic of the bearer''s ranged weapons.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Leagues of Votann' AND d.name = 'Needgaârd Oathband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'd5cef183-2cb1-c548-4b29-b3f187b32734',
       d.id,
       'Ancestral Crest',
       15,
       'Once per turn, when you target the bearer''s unit with the Command Re-roll Stratagem, the bearer can use this Enhancement. If it does, spend 1YP and reduces the CP cost of that Stratagem by 1CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Leagues of Votann' AND d.name = 'Needgaârd Oathband'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;
