-- Sync missing enhancements to production
-- Generated by scripts/generate-enhancement-sync.js
--
-- These enhancements exist in the seed file but were missing from production
-- due to BSData parser gaps (now fixed) and detachment ID mismatches
-- (where the seed used different detachment UUIDs than what production has).
--
-- Each insert looks up the detachment_id by (faction_name, detachment_name)
-- at runtime, so it works regardless of which UUID production has stored.

-- Imperial Knights :: Questor Forgepact (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'e5de888e-bc4e-c14f-c794-7b14c59fc817',
       d.id,
       'Vocifer Magnificat (Aura)',
       15,
       '**^^Imperial Knights^^** model only. While an enemy unit is within 6" of the bearer, worsen the Leadership characteristic of models in that unit by 1. While a friendly **^^Adeptus Mechanicus^^** unit is within 6" of the bearer, improve the Leadership characteristic of 1 models in that **^^Adeptus Mechanicus^^** unit by 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Imperial Knights' AND d.name = 'Questor Forgepact'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '6043264b-a7ad-fdd7-7ef1-ae28bf15de2b',
       d.id,
       'Magos Questoris',
       35,
       '**^^Tech‑Priest^^** model only. While the bearer is within 3" of one or more friendly **^^Imperial Knights^^** units, it has the Lone Operative ability. In your Command phase, select one friendly **^^Imperial Knights^^** model within 3" of the bearer. That model regains up to 2 lost wounds.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Imperial Knights' AND d.name = 'Questor Forgepact'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '76d948da-504a-938b-4855-dc1ab60f354e',
       d.id,
       'Knight of the Opus Machina',
       20,
       '**^^Imperial Knights^^** model only. Each time the bearer makes a ranged attack, if the bearer is within 6" of one or more friendly ADEPTUS MECHANICUS units, re‑roll a Hit roll of 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Imperial Knights' AND d.name = 'Questor Forgepact'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'fe09dd4e-f5d4-74e4-44de-ae5aa32a24e8',
       d.id,
       'Omnissian Champion',
       30,
       '**^^Imperial Knights^^** model only. Add 4 to the bearer’s Wounds characteristic.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Imperial Knights' AND d.name = 'Questor Forgepact'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Agents of the Imperium :: Veiled Blade Elimination Force (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'a4320cd1-b94d-78e5-daeb-0968e026e862',
       d.id,
       'Micromelta Round',
       45,
       'This model’s exitus rifle has the [ANTI‑MONSTER 4+] and [ANTI‑VEHICLE 4+] abilities.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Veiled Blade Elimination Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'c40d1ea4-28b8-01e8-0d83-20606aba539e',
       d.id,
       'Esoteric Explosives',
       40,
       'Each time this model is targeted with the Grenades Stratagem, 1 mortal wound is inflicted for each D6 roll of 3+ instead of for each 4+'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Veiled Blade Elimination Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '755be74a-8771-e4d1-e884-1f6a4c1f53c9',
       d.id,
       'Intra-neural Biotech',
       35,
       'Once per battle round, you can target this model with the Heroic Intervention or Counter‑offensive Stratagem for 0CP, and can do so even if you have already used that Stratagem on a different unit this phase.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Veiled Blade Elimination Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '90a03cca-57ca-8880-a52c-93fae1324433',
       d.id,
       'Decoy Targets',
       40,
       'Twice per battle, in your Movement phase, you can select one other friendly INFANTRY model that is on the battlefield and not within Engagement Range of one or more enemy units. The selected model is destroyed (ignoring any rules that are triggered when a model is destroyed) and this model is removed from the battlefield and set up again as close as possible to where that destroyed model was and not within Engagement Range of one or more enemy units. This ability cannot be used more than once in the same battle round.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Agents of the Imperium' AND d.name = 'Veiled Blade Elimination Force'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Genestealer Cults :: Xenocreed Congregation (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '97c1746f-6c17-1f4f-086d-4e7c3d7319ef',
       d.id,
       'Deeds That Speak to the Masses',
       25,
       '**^^Magus, Primus or Acolyte Iconward^^** model only. You start the battle with 2 additional Resurgence points.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Xenocreed Congregation'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'd695f33b-93ac-44e4-6e72-b05f61a4c018',
       d.id,
       'Gene-sire''s Reliquant',
       5,
       '**^^Magus, Primus or Acolyte Iconward^^** model only. You can re-roll Battle-shock tests taken for the bearer''s unit.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Xenocreed Congregation'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'c845c47a-a3e1-d5ff-1c6c-660ca30268fb',
       d.id,
       'Incendiary Inspiration',
       15,
       '**^^Magus, Primus or Acolyte Iconward^^** model only. The bearer''s unit is eligible to declare a charge in a turn in which it Advanced.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Xenocreed Congregation'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '62fdeac8-3142-5273-c13b-5105c26d460f',
       d.id,
       'Denunciator of Tyrants',
       25,
       '**^^Magus, Primus or Acolyte Iconward^^** model only. Each time a model in the bearer''s unit makes an attack that targets a **^^Character^^** unit, add 1 to the Hit Roll and add 1 to the Wound roll.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Xenocreed Congregation'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Genestealer Cults :: Biosanctic Broodsurge (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '54a65377-e85a-c184-4ff8-c182b1f6f02d',
       d.id,
       'Predatory Instincts',
       20,
       '**^^Abominant^^**, **^^Biophagus^^** or **^^Patriarch^^** model only. Models in the bearer''s unit have the Infiltrators ability and, once per battle round, you can target the bearer''s unit with the Heroic Intervention Stratagem for 0CP, and can do so even if you have already targeted a different unit with that Stratagem this phase.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Biosanctic Broodsurge'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '3a5e08e7-9d79-7ad3-e2a1-5ac411615e69',
       d.id,
       'Biomorph Adaption',
       25,
       '**^^Abominant ^^** or **^^Patriarch^^** model only. Improve the Armour Penetration and Damage characteristics of melee weapons equipped by the bearer by 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Biosanctic Broodsurge'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'de1862e6-3a79-2af6-2377-18477ddb2305',
       d.id,
       'Mutagenic Regeneration',
       10,
       '**^^Abominant^^**, **^^Biophagus^^** or **^^Patriarch^^** model only. In each Command phase, one model in the bearer''s unit regains 1 lost wound.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Biosanctic Broodsurge'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '72fb3d48-157d-602d-aba1-b0af335266b5',
       d.id,
       'Alien Majesty',
       15,
       '**^^Abominant^^**, **^^Biophagus^^** or **^^Patriarch^^** model only. While an enemy unit is in within Engagement Range of the bearer''s unit, subtract 1 from the Objective Control characteristic of models in that enemy unit (to a minimum of 1).'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Biosanctic Broodsurge'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Genestealer Cults :: Brood Brother Auxilia (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'e6e0f61d-dd22-3e80-3000-092f0360fbc3',
       d.id,
       'Martial Espionage',
       25,
       '**^^Genestealer Cults Infantry^^** model only. Once Per turn, when a friendly **^^Astra Militarum Infantry^^** or **^^Astra Militarum Mounted^^**unit within 9" of the bearer is selected to shoot, the bearer can use this Enhancement. If it does, until the end of the phase, improve the Armour Penetration characteristic of ranged weapons equipped by models in that unit by 1.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Brood Brother Auxilia'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '21834339-a158-3bb0-18f2-62bea0a2a6c3',
       d.id,
       'Adaptive Reprisal',
       15,
       '**^^Genestealer Cults Infantry^^** model only. Once per turn, you can target a friendly **^^Genestealer Cults^^** unit within 8" of the bearer with the Heroic Intervention Stratagem for 0CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Brood Brother Auxilia'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '8f6d3eab-1cda-b3e9-a19d-da4b4eaa9868',
       d.id,
       'The Hero Returned',
       20,
       '**^^Genestealer Cults Infantry^^** model only. Improve the Leadership and Objective Control characteristic of models in the bearer''s unit by 1'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Brood Brother Auxilia'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '6340c73c-8e2e-bddc-80b6-4ed1218c31be',
       d.id,
       'Fire-point Commander',
       10,
       '**^^Genestealer Cults Infantry^^** model only. Each time you target the bearer''s unit with the Fire Overwatch Stratagem, while resolving that stratagem, hits are successfully scored on a 5+.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Genestealer Cults' AND d.name = 'Brood Brother Auxilia'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

-- Necrons :: Pantheon of Woe (4 enhancements)
INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '91a6447f-9c37-a7ca-4525-d54de8695071',
       d.id,
       'Singularity Matrix',
       40,
       'Each time your opponent targets a unit from their army with a Stratagem, if that unit is within 12" of this model, increase the cost of that use of that Stratagem by 1CP.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Necrons' AND d.name = 'Pantheon of Woe'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '4ba0b232-4e42-b086-2907-697d3796a695',
       d.id,
       'Quantum Goad',
       30,
       'This model is eligible to declare a charge in a turn in which it Advanced.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Necrons' AND d.name = 'Pantheon of Woe'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT '77dddb8d-98e1-0ad2-f62f-892fcb503efa',
       d.id,
       'Animus Damper',
       20,
       'Once per turn, at the start of your opponent’s Shooting phase, select one enemy ^^**Vehicle^^** unit visible to the bearer. That unit must take a Leadership test. Until the end of the phase, each time a model in that unit makes an attack, subtract 1 from the Hit roll and, if that Leadership test was failed, subtract 1 from the Wound roll as well.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Necrons' AND d.name = 'Pantheon of Woe'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;

INSERT INTO public.enhancements (id, detachment_id, name, points, description)
SELECT 'b289ad18-1090-0e5e-25ac-0a1a2cd8efa4',
       d.id,
       'Relativistic Tether',
       25,
       'In your turn, each time this model is set up on the battlefield using the Deep Strike or Transdimensional Displacement abilities, it can be set up anywhere on the battlefield that is more than 6" horizontally away from all enemy units. When doing so, if this model is set up within 9" of one or more enemy units, until the end of the turn, it is not eligible to declare a charge.'
FROM public.detachments d
JOIN public.factions f ON d.faction_id = f.id
WHERE f.name = 'Necrons' AND d.name = 'Pantheon of Woe'
ON CONFLICT (id) DO UPDATE SET
  detachment_id = EXCLUDED.detachment_id,
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  description = EXCLUDED.description;
